PERSONS = [
    {
        "id": 1,
        "fullname": "Ara Clutram",
        "email": "aclutram0@merriam-webster.com",
        "gender": "Male",
        "jobtitles": [{"title": "Engineer", "date_start": "2024-02-01"}],
    },
    {
        "id": 2,
        "fullname": "Tabatha Chittem",
        "email": "tchittem1@shop-pro.jp",
        "gender": "Female",
        "jobtitles": [{"title": "Teacher", "date_start": "2024-02-01"}],
    },
    {
        "id": 3,
        "fullname": "Cosimo Manus",
        "email": "cmanus2@merriam-webster.com",
        "gender": "Male",
        "jobtitles": [{"title": "Engineer", "date_start": "2024-02-01"}],
    },
    {
        "id": 4,
        "fullname": "Luciana Lorentzen",
        "email": "llorentzen3@vimeo.com",
        "gender": "Agender",
        "jobtitles": [{"title": "Software Developer", "date_start": "2024-02-01"}],
    },
    {
        "id": 5,
        "fullname": "Salem Scoates",
        "email": "sscoates4@blog.com",
        "gender": "Male",
        "jobtitles": [{"title": "Engineer", "date_start": "2024-02-01"}],
    },
    {"id": 6, "fullname": "Wat Fane", "email": "wfane5@cpanel.net", "gender": "Male"},
    {
        "id": 7,
        "fullname": "Rudie Guilayn",
        "email": "rguilayn6@japanpost.jp",
        "gender": "Male",
        "jobtitles": [{"title": "Engineer", "date_start": "2024-02-01"}],
    },
    {
        "id": 8,
        "fullname": "Isis Grason",
        "email": "igrason7@youtu.be",
        "gender": "Female",
        "jobtitles": [{"title": "Engineer", "date_start": "2024-02-01"}],
    },
    {
        "id": 9,
        "fullname": "Sibeal Diperaus",
        "email": "sdiperaus8@gmpg.org",
        "gender": "Female",
        "jobtitles": [{"title": "Doctor", "date_start": "2024-02-01"}],
    },
    {
        "id": 10,
        "fullname": "Amalle Cicculini",
        "email": "acicculini9@mit.edu",
        "gender": "Female",
        "jobtitles": [{"title": "Mechanic", "date_start": "2024-02-01"}],
    },
]
